import type { LucideIcon } from "lucide-react";
import { Building2, CalendarDays, HeartHandshake, ShieldCheck, Sparkles, Users, Video } from "lucide-react";
import type { OrganizationSizeBand } from "@yoga-app/shared";

export const CORPORATE_TEAM_SIZE_LABELS: Record<OrganizationSizeBand, string> = { "5-10": "5–10 employees", "10-50": "10–50 employees", "50-100": "50–100 employees", "100+": "100+ employees" };
export const CORPORATE_HERO_POINTS = [["Live", "Teacher-led online practice"], ["Flexible", "Employee access and invitations"], ["Dedicated", "Organization-exclusive classes"], ["Simple", "Sales-supported per-seat pricing"]] as const;
export const CORPORATE_WHY_CARDS: Array<{ icon: LucideIcon; title: string; copy: string }> = [
  { icon: HeartHandshake, title: "More human than a content library", copy: "Live teachers bring presence and guidance to every session." }, { icon: Users, title: "Made for every starting point", copy: "Employees can join from wherever they are in their yoga journey." }, { icon: CalendarDays, title: "A repeatable wellbeing rhythm", copy: "Create regular moments your people can return to." }, { icon: Building2, title: "Designed for HR to operate", copy: "Set up access, invite people, and manage your organization in one place." },
];
export const CORPORATE_INCLUDED_CARDS: Array<{ icon: LucideIcon; title: string; copy: string }> = [
  { icon: Video, title: "Live group yoga", copy: "Scheduled online sessions with an instructor—not a recorded video library." }, { icon: Sparkles, title: "India’s best yoga teachers", copy: "Give your team access to exceptional India-based yoga teachers through the platform." }, { icon: HeartHandshake, title: "Diet plans", copy: "Practical diet guidance to complement your team’s yoga practice and wellbeing goals." }, { icon: Users, title: "Sponsored employee access", copy: "Purchase seats for your organization and invite employees by email." }, { icon: CalendarDays, title: "Organization classes", copy: "Run dedicated live classes for your organization when shared practice suits your team." }, { icon: Building2, title: "Simple administration", copy: "Manage members and view scheduled organization classes from your workspace." }, { icon: ShieldCheck, title: "Transparent plan setup", copy: "Receive a sales-supported, per-seat proposal before billing is activated." },
];
export const CORPORATE_ROLLOUT_STEPS = [["01", "Book a free team demo", "Tell us about your team and the wellbeing experience you want to create."], ["02", "Agree your organization plan", "We align on your access needs and share a per-seat proposal."], ["03", "Invite your people", "Your organization admin invites employees and manages access."], ["04", "Start practising live", "Employees join live sessions and dedicated organization classes can begin."]] as const;
export const CORPORATE_ACCESS_OPTIONS = [
  { tag: "Option A", title: "Sponsor employee seats", copy: "Purchase a block of sponsored seats, then invite employees to activate them.", points: ["A clear per-seat purchase", "Employee invitations by email", "Seat and member administration in your workspace"] }, { tag: "Option B", title: "Support employee self-pay", copy: "Offer employees a negotiated self-pay benefit through an organization coupon.", points: ["A company-specific benefit", "Employees use their organization coupon", "A dedicated organization space for your team"] },
] as const;
export const CORPORATE_HR_TOOLS = [["Members and invitations", "Invite employees and manage organization membership."], ["Sponsored seats", "Purchase and allocate access for your team."], ["Upcoming organization classes", "See dedicated upcoming sessions and their attendees."], ["Organization coupon", "Share a negotiated self-pay benefit when relevant."], ["Billing approval", "Receive organization pricing after the team finalizes your proposal."]] as const;
export const CORPORATE_FAQS = [["What does the free team demo include?", "Tell us about your team and we’ll coordinate a possible live session for interested employees. There is no purchase step in the request form."], ["How does a company provide access?", "After a corporate plan is agreed, your organization admin can purchase sponsored seats and invite employees by email."], ["Can classes be exclusive to our organization?", "Yes. The platform supports organization-exclusive live classes, so your team can practise together in a dedicated session."], ["How is pricing decided?", "Pricing is finalized per organization after we understand your team size and access needs."], ["What can HR manage?", "Organization admins can manage invitations, seats, and upcoming organization classes from their workspace."]] as const;
